### ISSUE TITLE
SearchEverywhere broken in 2022.3: NoSuchMethodError

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#100]
Plugin Version: 0.6.7
IntelliJ Version: PyCharm 2022.3
IntelliJ Build: PY-223.7571.203

<details><summary>java.lang.NoSuchMethodError: 'void com.intellij.ide.actions.searcheverywhere.FoundItemDescriptor.<init>(java.lang.Object, int, double)'</summary>

```
java.lang.NoSuchMethodError: 'void com.intellij.ide.actions.searcheverywhere.FoundItemDescriptor.<init>(java.lang.Object, int, double)'
	at at.wtioit.intellij.plugins.odoo.search.OdooFoundItemDescriptor.<init>(OdooFoundItemDescriptor.java:10)
	at at.wtioit.intellij.plugins.odoo.search.OdooFoundItemDescriptor.weighted(OdooFoundItemDescriptor.java:23)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.lambda$fetchWeightedElements$1(OdooSEContributor.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:847)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.fetchWeightedElements(OdooSEContributor.java:78)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:182)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

reproduced #99

**Comment by ap-wtioit** [comment]
fixed in 0.6.8 (pending jetbrains approval)
