### ISSUE TITLE
getDefiningElement NullPointerException

### ISSUE THREAD

**Issue by xMichaelSilvax** [wt-io-it/odoo-pycharm-plugin#107]
Plugin Version: 0.6.8
IntelliJ Version: PyCharm 2022.3
IntelliJ Build: PY-223.7571.203

<details><summary>java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "exceptionSupplier" is null</summary>

```
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "exceptionSupplier" is null
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:92)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$4(OdooModelImpl.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:47)
	at at.wtioit.intellij.plugins.odoo.records.index.OdooDeserializedRecordImpl.getDefiningElement(OdooDeserializedRecordImpl.java:55)
	at at.wtioit.intellij.plugins.odoo.AbstractOdooCompletionContributor.lambda$suggestRecordXmlId$1(AbstractOdooCompletionContributor.java:119)
	at at.wtioit.intellij.plugins.odoo.WithinProject.run(WithinProject.java:25)
	at at.wtioit.intellij.plugins.odoo.AbstractOdooCompletionContributor.suggestRecordXmlId(AbstractOdooCompletionContributor.java:118)
	at at.wtioit.intellij.plugins.odoo.OdooXmlCompletionContributor.fillCompletionVariants(OdooXmlCompletionContributor.java:22)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
	...
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	...
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by ap-wtioit** [comment]
@xMichaelSilvax this seems to be the same as #30 and was fixed in 0.6.9, can you update the plugin?
