### ISSUE TITLE
Windows: Unexpected internal error near index 1

### ISSUE THREAD

**Issue by hselmi** [wt-io-it/odoo-pycharm-plugin#15]
Plugin Version: 0.5.9
IDEA Version: PyCharm 2021.1.1

<details><summary>java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
</summary>

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	...
	at java.base/java.lang.String.split(String.java:2364)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectory(OdooModuleServiceImpl.java:106)
	at at.wtioit.intellij.plugins.odoo.modules.index.OdooDeserializedModuleImpl.getDirectory(OdooDeserializedModuleImpl.java:64)
	at at.wtioit.intellij.plugins.odoo.WithinProject.call(WithinProject.java:15)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:38)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:42)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:192)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	...
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:773)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.foreignResults(PyResolveImportUtil.kt:194)
	...
	at com.jetbrains.python.pyi.PyiRelatedItemLineMarkerProvider.collectNavigationMarkers(PyiRelatedItemLineMarkerProvider.java:33)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:31)
	...
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	...
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

**Comment by ap-wtioit** [comment]
thanks for reporting the issue,

could you test the bugfix for running on windows described here: https://github.com/wt-io-it/odoo-pycharm-plugin/issues/10#issuecomment-1031336211

that would help a lot.

**Comment by ap-wtioit** [comment]
Jetbrains just approved the plugin version 0.5.10. This should be fixed now.
