### ISSUE TITLE
SearchEverywhere, Intellij: missing project information (@NotNull)

### ISSUE THREAD

**Issue by fromero** [wt-io-it/odoo-pycharm-plugin#16]
Plugin Version: 0.5.9
IDEA Version: IntelliJ IDEA 2021.3.2

<details><summary>java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/openapi/components/ServiceManager.getService must not be null</summary>

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/openapi/components/ServiceManager.getService must not be null
	at com.intellij.openapi.components.ServiceManager.$$$reportNull$$$0(ServiceManager.java)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java)
	at at.wtioit.intellij.plugins.odoo.modules.index.OdooDeserializedModuleImpl.getDirectory(OdooDeserializedModuleImpl.java:63)
	at at.wtioit.intellij.plugins.odoo.modules.search.OdooModulePsiElement.getLanguage(OdooModulePsiElement.java:91)
	at com.intellij.ide.JavaClassAndFileEqualityProvider.areEqual(JavaClassAndFileEqualityProvider.java:22)
	at com.intellij.ide.actions.searcheverywhere.AbstractEqualityProvider.lambda$compareItems$0(AbstractEqualityProvider.java:18)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	...
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
	at com.intellij.ide.actions.searcheverywhere.AbstractEqualityProvider.compareItems(AbstractEqualityProvider.java:25)
	...
	at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$Companion$composite$1$compareItems$1.invoke(SEResultsEqualityProvider.kt:32)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$Companion$composite$1.compareItems(SEResultsEqualityProvider.kt:48)
	...
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.lambda$run$1(MixedResultsSearcher.java:188)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.lambda$fetchElements$0(OdooSEContributor.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:839)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.fetchElements(OdooSEContributor.java:59)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	...
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
if you want you can try to install the odoo-plugin.jar from https://github.com/wt-io-it/odoo-pycharm-plugin/tree/master-0.5.10_fix_indexing_error following the alternate installing instructions in the readme.

**Comment by ap-wtioit** [comment]
Jetbrains just approved the plugin version 0.5.10. This should be fixed now.
