### ISSUE TITLE
Windows: Unexpected internal error near index 1

### ISSUE THREAD

**Issue by yeromt2** [wt-io-it/odoo-pycharm-plugin#17]
Plugin Version: 0.5.9
IDEA Version: PyCharm 2021.3

<details><summary>java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
</summary>

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	...
	at java.base/java.lang.String.split(String.java:2364)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectory(OdooModuleServiceImpl.java:106)
	at at.wtioit.intellij.plugins.odoo.modules.index.OdooDeserializedModuleImpl.getDirectory(OdooDeserializedModuleImpl.java:64)
	at at.wtioit.intellij.plugins.odoo.WithinProject.call(WithinProject.java:15)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:51)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:199)
	...
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

**Comment by ap-wtioit** [comment]
thanks for reporting the issue,

could you test the bugfix for running on windows described here: https://github.com/wt-io-it/odoo-pycharm-plugin/issues/10#issuecomment-1031336211

that would help a lot.

**Comment by ap-wtioit** [comment]
Jetbrains just approved the plugin version 0.5.10. This should be fixed now.
