### ISSUE TITLE
Odoo 16.0 Cannot find defining elements for web_dashboard.dashboard

### ISSUE THREAD

**Issue by eviltweats** [wt-io-it/odoo-pycharm-plugin#175]
<-- If you remember any details about how the error can be reproduced please add them -->

Plugin Version: 0.6.11
IntelliJ Version: PyCharm 2022.3.3
IntelliJ Build: PC-223.8836.43

<details><summary>Unhandled exception in [StandaloneCoroutine{Cancelling}@473d2f9a, EDT]</summary>

```
at.wtioit.intellij.plugins.odoo.OdooPluginError: Cannot find defining elements for web_dashboard.dashboard with files [file://D:/Projects/Odoo16/odoo_web_tools/web_dashboard/views/container_views.xml, file://D:/Projects/Odoo16/odoo_web_tools/web_dashboard/models/container.py]
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$7(OdooModelImpl.java:109)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:109)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$5(OdooModelImpl.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:49)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getOdooModel(OdooGoToDeclarationHandler.java:152)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getOdooModel(OdooGoToDeclarationHandler.java:137)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTarget(OdooGoToDeclarationHandler.java:45)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationHandlerBase.getGotoDeclarationTargets(GotoDeclarationHandlerBase.java:14)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTargets(OdooGoToDeclarationHandler.java:33)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProvidersInner(gtdProviders.kt:30)
	...
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invokeSuspend(InternalReadAction.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	...
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@473d2f9a, EDT]
```
</details>

**Comment by ap-wtioit** [comment]
Notes:
* web_dashboard is not present in our 16.0 versions (probably taken from 15.0)
* could be when hovering (while holding CTRL) over web_dashboard/views/dashboard.rng
  ```xml
    <start>
        <ref name="dashboard" />
    </start>
  ```

**Comment by ap-wtioit** [comment]
@eviltweats which sources are you using for web_dashboard, Odoo Enterprise 15.0 or custom ones?

**Comment by eviltweats** [comment]
Actually I was working on Odoo v16.

**Comment by ap-wtioit** [comment]
Can you tell me where your web_dashboard plugin directory is coming from? (I cannot find it on https://github.com/odoo/odoo?search=1) This should help me reproduce the bug and fix it.

**Comment by eviltweats** [comment]
Its a custom module.

**Comment by ap-wtioit** [comment]
Can you hover while holding CTRL over various elements in your container_views.xml and tell my if the exception happens again? And if so, hint my to an XML Structure that may cause this problem?
