### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by borisdamevin** [wt-io-it/odoo-pycharm-plugin#18]
Plugin Version: 0.5.9
IDEA Version: PyCharm 2022.1 EAP

<details><summary>kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@d7010f2
</summary>

```
kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@d7010f2
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	...
	at java.base/java.lang.String.split(String.java:2364)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectory(OdooModuleServiceImpl.java:106)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.lambda$getModule$1(OdooModuleServiceImpl.java:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModule(OdooModuleServiceImpl.java:73)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$0(OdooModelImpl.java:58)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	...
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$4(OdooModelImpl.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:49)
	at at.wtioit.intellij.plugins.odoo.models.search.OdooModelPsiElement.getIcon(OdooModelPsiElement.java:326)
	at com.intellij.ide.util.PsiElementListCellRenderer.getIcon(PsiElementListCellRenderer.java:342)
	...
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2.invokeSuspend(ReadAction.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	...
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
		... 48 more
	Suppressed: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
		... 48 more
	Suppressed: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
		... 48 more
	Suppressed: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
		... 48 more
	Suppressed: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
		... 48 more
```
</details>

**Comment by ap-wtioit** [comment]
this has the same root cause as https://github.com/wt-io-it/odoo-pycharm-plugin/issues/10
