### ISSUE TITLE
NullPointerException during SearchEverywhere

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#23]
Plugin Version: 0.6.0-SNAPSHOT
IDEA Version: PyCharm 2021.3.3

<details><summary>java.lang.NullPointerException</summary>

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at at.wtioit.intellij.plugins.odoo.records.search.OdooRecordPsiElement.<init>(OdooRecordPsiElement.java:30)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.lambda$fetchElements$2(OdooSEContributor.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:839)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.fetchElements(OdooSEContributor.java:82)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
also reproduced in 2022.1 PyCharm
