### ISSUE TITLE
Exception when name / inherit contains a List of Lists

### ISSUE THREAD

**Issue by edsondeveloop** [wt-io-it/odoo-pycharm-plugin#25]
Plugin Version: 0.5.12
IDEA Version: PyCharm 2021.3.3

<details><summary>java.lang.Throwable: Unknown string value class: class com.jetbrains.python.psi.impl.PyListLiteralExpressionImpl</summary>

```
java.lang.Throwable: Unknown string value class: class com.jetbrains.python.psi.impl.PyListLiteralExpressionImpl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.getStringValueForValueChild(OdooModelUtil.java:73)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:42)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:28)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelDefinition.<init>(OdooModelDefinition.java:17)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.lambda$mapWatched$0(OdooModelFileIndex.java:114)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:50)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:111)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:14)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:306)
	...
	at com.intellij.util.indexing.FileBasedIndexEx.getAllKeys(FileBasedIndexEx.java:120)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.hasModel(OdooModelServiceImpl.java:66)
	at at.wtioit.intellij.plugins.odoo.models.inspection.MissingModelDefinitionInspection$1.visitElement(MissingModelDefinitionInspection.java:55)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:208)
	...
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	...
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

**Comment by ap-wtioit** [comment]
@edsondeveloop  thanks for reporting this. Could you check if Find in Files [CTRL]+[SHIFT]+[F] with the following regex finds anything and report the (anonymized) results back to me here: `\s_(name|inherit)\s*=\s*\[\s*\[`

This would help me writing a better fix for this. (Or verify that it's already fixed in 0.5.13 (not yet approved by JetBrains))
