### ISSUE TITLE
Unknown string value class: class com.jetbrains.python.psi.impl.PyTupleExpressionImpl

### ISSUE THREAD

**Issue by mdark1001** [wt-io-it/odoo-pycharm-plugin#26]
Plugin Version: 0.5.13
IDEA Version: PyCharm 2022.1.1

<details><summary>java.lang.Throwable: Unknown string value class: class com.jetbrains.python.psi.impl.PyTupleExpressionImpl</summary>

```
java.lang.Throwable: Unknown string value class: class com.jetbrains.python.psi.impl.PyTupleExpressionImpl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.getStringValueForValueChild(OdooModelUtil.java:114)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:42)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:28)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelDefinition.<init>(OdooModelDefinition.java:17)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.lambda$mapWatched$0(OdooModelFileIndex.java:114)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:50)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:111)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:14)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:308)
	...
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
@mdark1001 thanks for your report, i could reproduce the error in tests and am preparing a bugfix for this.

**Comment by ap-wtioit** [comment]
i just pushed 0.5.14 to the marketplace for review, if you are eager to test the new version you can also install it from the jar file in [0.5.14](https://github.com/wt-io-it/odoo-pycharm-plugin/tree/v0.5.14) by following the instructions in the readme.

**Comment by ap-wtioit** [comment]
0.5.14 got approved and now is available in the marketplace, this issue should be fixed after updating to the new version.
