### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by jaronemo** [wt-io-it/odoo-pycharm-plugin#27]
Plugin Version: 0.5.13
IDEA Version: PyCharm 2022.1.1

<details><summary>java.lang.RuntimeException: PCE is not expected in non-cancellable section execution</summary>

```
java.lang.RuntimeException: PCE is not expected in non-cancellable section execution
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:246)
	...
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:132)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.lambda$getModule$0(OdooModuleServiceImpl.java:58)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModule(OdooModuleServiceImpl.java:55)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:49)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:199)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.openapi.progress.JobCanceledException: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelling}@31a05861
	at com.intellij.openapi.progress.Cancellation.checkCancelled(Cancellation.java:44)
	...
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	... 150 more
Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@31a05861
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:156)
	...
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

**Comment by ap-wtioit** [comment]
Notes: not easily reproducable, my best guesses, currently:
* it may happen when resolving gets cancelled because the file is updated
 * open a python file with imports like `from odoo.addons....` 
 * get pycharm to cancel the import resolving (e.g. by switching source code with git or something else)
* it may happen when typing in an import statement and completion for an old text is canceled
