### ISSUE TITLE
Type Hierarchy cannot not be loaded

### ISSUE THREAD

**Issue by hellozhangwei** [wt-io-it/odoo-pycharm-plugin#271]
Plugin Version: 0.6.11
IntelliJ Version: PyCharm 2023.1
IntelliJ Build: #PC-231.8109.197

<img width="590" alt="image" src="https://github.com/wt-io-it/odoo-pycharm-plugin/assets/11864498/8c9b907f-b897-4256-ba1f-74399753283c">

```
at.wtioit.intellij.plugins.odoo.OdooPluginError: Cannot find defining elements for res.config.settings with files [file:///Users/weizhang/Projects/tps/OCA/OCB/addons/stock_sms/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/account/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_sale_autocomplete/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/sale_management/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_payment/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/microsoft_outlook/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_ke_edi_tremol/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/snailmail/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/product_expiry/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/sale_timesheet/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/sale/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/event/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_sale_picking/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_loyalty/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/crm/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_it_edi/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/partner_autocomplete/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/snailmail_account/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/point_of_sale/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_es_edi_tbai/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/test_website/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_eg_edi_eta/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/sale_stock/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_sale/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_hr/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/mass_mailing/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_event_track/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/sale_project/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/project_timesheet_holidays/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/auth_totp_mail_enforce/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/project/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/fleet/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_event_jitsi/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_sale/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/hr_recruitment/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/account_payment_invoice_online_payment_patch/wizards/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/portal/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_pl_jpk/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_eu_oss/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/mrp/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/crm_iap_enrich/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_epson_printer/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/auth_password_policy/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/purchase/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/microsoft_calendar/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_payment_authorize/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_discount/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/stock/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/helpdesk/helpdesk_mgmt/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/hr_timesheet/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/base_vat/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/product/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/base_geolocalize/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_ch/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_adyen/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/hr/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_es_edi_sii/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_twitter/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/digest/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/base_setup/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_mx/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_slides/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/account_check_printing/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/iap/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/odoo/addons/base/models/res_config.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/auth_signup/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/stock_landed_costs/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_in_edi/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_sa_edi/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_sale_stock/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/analytic/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/product_images/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/hr_expense/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_id_efaktur/models/res_partner.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/google_gmail/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/mail/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/auth_oauth/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/google_recaptcha/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/lunch/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/auth_ldap/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/addons/odoo_website_helpdesk/models/res_config.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/pos_restaurant/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/hr_attendance/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/purchase_stock/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_payment_paypal/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_in/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/website_livechat/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/web_unsplash/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/l10n_in_edi_ewaybill/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/google_calendar/models/res_config_settings.py, file:///Users/weizhang/Projects/tps/OCA/OCB/addons/stock_account/models/res_config_settings.py]
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$7(OdooModelImpl.java:109)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:109)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.lambda$getDefiningElement$5(OdooModelImpl.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelImpl.getDefiningElement(OdooModelImpl.java:49)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.lambda$getModelForElement$8(OdooModelServiceImpl.java:69)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.getModelForElement(OdooModelServiceImpl.java:70)
	at at.wtioit.intellij.plugins.odoo.models.hierarchy.OdooModelTypeHierarchyTreeStructureUtil.buildChildren(OdooModelTypeHierarchyTreeStructureUtil.java:82)
	at at.wtioit.intellij.plugins.odoo.models.hierarchy.OdooModelSubTypesHierarchyTreeStructure.buildChildren(OdooModelSubTypesHierarchyTreeStructure.java:25)
	at com.intellij.ide.hierarchy.HierarchyTreeStructure.lambda$getChildElements$0(HierarchyTreeStructure.java:87)
	at com.intellij.ide.util.treeView.AbstractTreeUi.calculateYieldingToWriteAction(AbstractTreeUi.java:1713)
	at com.intellij.ide.hierarchy.HierarchyTreeStructure.getChildElements(HierarchyTreeStructure.java:87)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:410)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:328)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:322)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:342)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:431)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ap-wtioit** [comment]
Thanks for your report, can you tell me which plugin and ide version you are using:
* Help -> About
* File -> Settings (depending on your IDE version) -> Plugins -> Search for Odoo Autocompletion Support

This would make tracking down the bug (and fixing it) faster.

Edit:
Thanks for updating
