### ISSUE TITLE
ArrayIndexOutOfBoundsException when performing GoTo for empty M2NField declaration

### ISSUE THREAD

**Issue by netfxtech** [wt-io-it/odoo-pycharm-plugin#28]
Plugin Version: 0.5.13
IDEA Version: PyCharm 2021.2.1

<details><summary>java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0</summary>

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at at.wtioit.intellij.plugins.odoo.OdooModelPsiElementMatcherUtil.isOdooModelPsiElement(OdooModelPsiElementMatcherUtil.java:88)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTarget(OdooGoToDeclarationHandler.java:28)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationHandlerBase.getGotoDeclarationTargets(GotoDeclarationHandlerBase.java:14)
	...
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by bigbear3001** [comment]
@netfxtech thanks for reporting this, it is fixed in 0.5.15 with https://github.com/wt-io-it/odoo-pycharm-plugin/commit/60af3ec1a923a1671e5651856625aef7f1343515 (pending approval by jetbrains). if you are eager to test it feel free to use the plugin jar file from https://github.com/wt-io-it/odoo-pycharm-plugin/tree/v0.5.15
