### ISSUE TITLE
Freeze when using SearchEverywhere

### ISSUE THREAD

**Issue by jond-odoo** [wt-io-it/odoo-pycharm-plugin#306]
I searched in the code for `consistent,`. It happens pretty often that I can't do anything when I search something so I have to quit Pycharm and kill the Python process, it's quite annoying.

Plugin Version: 0.6.11
IntelliJ Version: PyCharm 2023.2
IntelliJ Build: PY-232.8660.197

<details><summary>java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiElement.isValid()" because the return value of "java.util.function.Supplier.get()" is null</summary>

```
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiElement.isValid()" because the return value of "java.util.function.Supplier.get()" is null
	at at.wtioit.intellij.plugins.odoo.search.AbstractOdooPsiElement.lambda$isValid$2(AbstractOdooPsiElement.java:217)
	at at.wtioit.intellij.plugins.odoo.WithinProject.call(WithinProject.java:12)
	at at.wtioit.intellij.plugins.odoo.search.AbstractOdooPsiElement.isValid(AbstractOdooPsiElement.java:216)
	at com.intellij.searchEverywhereMl.ranking.features.statistician.SearchEverywhereSymbolStatistician$getContextName$1.invoke(SearchEverywhereSymbolStatistician.kt:20)
	...
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.lambda$run$0(MixedResultsSearcher.java:185)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.lambda$fetchWeightedElements$2(OdooSEContributor.java:121)
	at at.wtioit.intellij.plugins.odoo.WithinProject.run(WithinProject.java:25)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.lambda$fetchWeightedElements$3(OdooSEContributor.java:101)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.fetchWeightedElements(OdooSEContributor.java:100)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	...
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	...
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by ap-wtioit** [comment]
@jond-odoo do i understand you correctly that pycharm is hanging (locked), e.g. like this:
![image](https://github.com/user-attachments/assets/777f3453-8338-4292-a9f8-57c76625d6ed)

how do you kill the python process to get it to trigger the error report with the stacktrace or is the stacktrace unrelated?

**Comment by ap-wtioit** [comment]
Notes for me:
Steps to produce the hanging PyCharm
* PyCharm 2024.1.4
* Open Odoo 17.0 as project in PyCharm
* configure python interpreter (venv)
* install requirements.txt
* close Odoo project in PyCharm
* open Odoo project in PyCharm again
* trigger SE with [SHIFT] [SHIFT]
* try to type `consistent,` (could not get it to the second letter)

**Comment by jond-odoo** [comment]
Indeed, it's exactly this behavior. I kill the process in my terminal with "sudo kill <PID>" founding PID with the command "netstat -tulpn"

**Comment by ap-wtioit** [comment]
ThreadDumps from my workspace
[threadDump-20240731-132330.txt](https://github.com/user-attachments/files/16440645/threadDump-20240731-132330.txt)
[threadDump-20240731-132335.txt](https://github.com/user-attachments/files/16440646/threadDump-20240731-132335.txt)
[threadDump-20240731-132340.txt](https://github.com/user-attachments/files/16440647/threadDump-20240731-132340.txt)
[threadDump-20240731-123756.txt](https://github.com/user-attachments/files/16440651/threadDump-20240731-123756.txt)
[threadDump-20240731-123801.txt](https://github.com/user-attachments/files/16440652/threadDump-20240731-123801.txt)
[threadDump-20240731-123806.txt](https://github.com/user-attachments/files/16440653/threadDump-20240731-123806.txt)
