### ISSUE TITLE
OdooSEContributor freezes UI

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#31]
it interferes with the "Flushing Daemon":
arround 20 (yesterday, 18 today) SE-SearchTask-OdooSEContributor interlock with one Flushing Daemon
```
...
"SE-SearchTask-OdooSEContributor" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.util.concurrent.locks.ReentrantLock$NonfairSync@4fce3c49 owned by "Flushing Daemon" Id=511
	at java.base@11.0.15/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.15/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.15/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base@11.0.15/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	at java.base@11.0.15/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	at java.base@11.0.15/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:231)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:264)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:23)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.read(TransientChangesIndexStorage.java:191)
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java:231)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getData(CompositeInvertedIndexBase.java:110)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$12(FileBasedIndexEx.java:406)
	at com.intellij.util.indexing.FileBasedIndexEx$$Lambda$4596/0x00000008027c8440.convert(Unknown Source)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$7(FileBasedIndexEx.java:304)
	at com.intellij.util.indexing.FileBasedIndexEx$$Lambda$4292/0x0000000802587840.compute(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$8(FileBasedIndexEx.java:304)
	at com.intellij.util.indexing.FileBasedIndexEx$$Lambda$4291/0x0000000802587440.compute(Unknown Source)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:42)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:303)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:404)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:373)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1113)
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:132)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndex.getAllKeys(OdooIndex.java:62)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleNames(OdooModuleServiceImpl.java:53)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.lambda$fetchElements$1(OdooSEContributor.java:64)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor$$Lambda$9024/0x000000080382ec40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at at.wtioit.intellij.plugins.odoo.search.OdooSEContributor.fetchElements(OdooSEContributor.java:63)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.util.ConcurrencyUtil$$Lambda$716/0x000000080091b040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base@11.0.15/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@11.0.15/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.15/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base@11.0.15/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base@11.0.15/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.15/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)
...
"Flushing Daemon" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@31628862 owned by "SE-SearchTask-OdooSEContributor" Id=488
	at java.base@11.0.15/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.15/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.15/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base@11.0.15/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	at java.base@11.0.15/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	at java.base@11.0.15/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:959)
	at com.intellij.util.io.PersistentMapImpl.force(PersistentMapImpl.java:728)
	at com.intellij.util.indexing.impl.ValueContainerMap.force(ValueContainerMap.java:95)
	at com.intellij.util.indexing.impl.MapIndexStorage.lambda$flush$0(MapIndexStorage.java:221)
	at com.intellij.util.indexing.impl.MapIndexStorage$$Lambda$2985/0x0000000801cf9840.run(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:243)
	at com.intellij.util.indexing.impl.MapIndexStorage.flush(MapIndexStorage.java:218)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.flush(VfsAwareMapIndexStorage.java:78)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.flush(TransientChangesIndexStorage.java:116)
	at com.intellij.util.indexing.impl.MapReduceIndex.doFlush(MapReduceIndex.java:186)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.doFlush(VfsAwareMapReduceIndex.java:358)
	at com.intellij.util.indexing.impl.MapReduceIndex.flush(MapReduceIndex.java:165)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.flush(CompositeInvertedIndexBase.java:274)
	at com.intellij.util.indexing.FileBasedIndexImpl.flushAllIndices(FileBasedIndexImpl.java:744)
	at com.intellij.util.indexing.FileBasedIndexImpl$7.run(FileBasedIndexImpl.java:2002)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.util.ConcurrencyUtil$$Lambda$716/0x000000080091b040.run(Unknown Source)
	at java.base@11.0.15/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@11.0.15/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:226)
	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.15/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base@11.0.15/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base@11.0.15/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.15/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)
...
```

**Comment by bigbear3001** [comment]
fixed with search index refactoring
