### ISSUE TITLE
Indexing: Unknown string value class: class com.jetbrains.python.psi.impl.PyConditionalExpressionImpl

### ISSUE THREAD

**Issue by Levizar** [wt-io-it/odoo-pycharm-plugin#32]
Plugin Version: 0.5.15
IDEA Version: PyCharm 2022.1.2

<details><summary>java.lang.Throwable: Unknown string value class: class com.jetbrains.python.psi.impl.PyConditionalExpressionImpl</summary>

```
java.lang.Throwable: Unknown string value class: class com.jetbrains.python.psi.impl.PyConditionalExpressionImpl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.getStringValueForValueChild(OdooModelUtil.java:114)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:42)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:28)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelDefinition.<init>(OdooModelDefinition.java:17)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.lambda$mapWatched$0(OdooModelFileIndex.java:114)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:50)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:111)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:14)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:308)
	...
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
@Levizar thanks for reporting this. I fixed the issue in the upcoming 0.5.16 version. If you are eager to test it before it gets approved by JetBrains in the Marketplace you can install the odoo_plugin.jar from the [v0.5.16](https://github.com/wt-io-it/odoo-pycharm-plugin/tree/v0.5.16) tag

**Comment by ap-wtioit** [comment]
re-opening until 0.5.16 is approved and available in the marketplace

**Comment by ap-wtioit** [comment]
version 0.5.16 is now available in the [marketplace](https://plugins.jetbrains.com/plugin/13083-odoo-autocompletion-support/versions)
