### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by onduex** [wt-io-it/odoo-pycharm-plugin#34]
Plugin Version: 0.5.16
IDEA Version: PyCharm 2022.1.2

<details><summary>com.intellij.diagnostic.PluginException: at.wtioit.intellij.plugins.odoo.models.inspection.MissingModelDefinitionInspection [Plugin: at.wtioit.intellij.plugins.odoo]</summary>

```
com.intellij.diagnostic.PluginException: at.wtioit.intellij.plugins.odoo.models.inspection.MissingModelDefinitionInspection [Plugin: at.wtioit.intellij.plugins.odoo]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:909)
	...
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	...
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: at.wtioit.intellij.plugins.odoo.models.inspection.MissingModelDefinitionInspection
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1472)
	...
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:901)
	... 29 more
```
</details>

**Comment by ap-wtioit** [comment]
@onduex did you install the plugin update via marketplace? could you add the information about the JVM you are using? In PyCharm -> Help -> About, remove the license info if present, should look like this:
```
PyCharm 2022.1.2 (Professional Edition)
Build #PY-221.5787.24, built on May 31, 2022
Licensed to ...
Subscription is active until ...
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-120-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 16
Non-Bundled Plugins:
    zielu.gittoolbox (212.9.0)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    mobi.hsz.idea.gitignore (4.4.0)
    dev.meanmail.plugin.nginx-intellij-plugin (2021.3-2022.1)
    com.perl5 (2022.1.1)
    com.intellij.ideolog (203.0.30.0)
    pro.bashsupport (2.1.8.221)
    at.wtioit.intellij.plugins.odoo (0.5.16)

Current Desktop: ubuntu:GNOME
```

**Comment by ap-wtioit** [comment]
Notes:
Downgraded from 0.6.0-SNAPSHOT -> 0.5.16 via jar file, could not reproduce
Downgraded from 0.5.16 -> 0.5.14 via jar file and updated from 0.5.14 -> 0.5.16 via marketplace, could not reproduce
Could there be a classloader issue? (the class is present in both jars)
