### ISSUE TITLE
getModuleDirectorySlow java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by farazc2h** [wt-io-it/odoo-pycharm-plugin#35]
Plugin Version: 0.5.16
IDEA Version: PyCharm 2022.1.2

<details><summary>
Details: Current thread: Thread[JobScheduler FJ pool 1/9,4,main] 1288197260
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 995054936</summary>

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:770)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:299)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:249)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:233)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1089)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.lambda$getModels$0(OdooModelServiceImpl.java:31)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1642)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.base/java.util.Spliterators$IteratorSpliterator.trySplit(Spliterators.java:1776)
	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:114)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

**Comment by ap-wtioit** [comment]
@farazc2h do you remember when the error happened? did you search for something, open a specific file, reopen the workspace, ...?

**Comment by ap-wtioit** [comment]
fixed with https://github.com/wt-io-it/odoo-pycharm-plugin/issues/33 (620508fc55b16691df8772f3239f21fd4f06be56 and 9be48e2c3afc109a75a290b1a34017d18f2579f7, 0.5.18)

**Comment by ap-wtioit** [comment]
0.5.18 is now available in jetbrains marketplace https://plugins.jetbrains.com/plugin/13083-odoo-autocompletion-support
