### ISSUE TITLE
getModuleDirectorySlow java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by mah007** [wt-io-it/odoo-pycharm-plugin#38]
Plugin Version: 0.5.13
IDEA Version: PyCharm 2022.1.3

<details><summary>java.lang.Throwable: Assertion failed</summary>

```
java.lang.Throwable: Assertion failed
	->at com.intellij...assertTrue(Logger.java:218)
	...
	->at com.intellij...getFilesByName(FilenameIndex.java:79)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.lambda$getModuleDirectorySlow$3(OdooModuleServiceImpl.java:136)
	->at com.intellij...runReadAction(ApplicationImpl.java:920)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectorySlow(OdooModuleServiceImpl.java:134)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectory(OdooModuleServiceImpl.java:129)
	at at.wtioit.intellij.plugins.odoo.modules.index.OdooDeserializedModuleImpl.getDirectory(OdooDeserializedModuleImpl.java:64)
	at at.wtioit.intellij.plugins.odoo.WithinProject.call(WithinProject.java:15)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:38)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:42)
	->at com.jetbrains...invoke(PyResolveImportUtil.kt:199)
	...
	->at com.jetbrains...getType(PyTargetExpressionImpl.java:128)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyTargetExpression.getType(OdooPyTargetExpression.java:19)
	->at com.jetbrains...lambda$getType$0(TypeEvalContext.java:176)
	...
	->at com.jetbrains...getType(PyReferenceExpressionImpl.java:229)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyReferenceExpression.getType(OdooPyReferenceExpression.java:89)
	->at com.jetbrains...lambda$getType$0(TypeEvalContext.java:176)
	...
	->at com.jetbrains...getType(TypeEvalContext.java:165)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.resolveInner(OdooPyQualifiedReference.java:72)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.lambda$multiResolve$0(OdooPyQualifiedReference.java:55)
	->at com.intellij...computePreventingRecursion(RecursionManager.java:114)
	...
	->at com.intellij...doPreventingRecursion(RecursionManager.java:68)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.lambda$multiResolve$1(OdooPyQualifiedReference.java:55)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:231)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:242)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.multiResolve(OdooPyQualifiedReference.java:51)
	->at com.jetbrains...multiResolveTopPriority(PyUtil.java:527)
	...
	->at com.jetbrains...getType(PyReferenceExpressionImpl.java:217)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyReferenceExpression.getType(OdooPyReferenceExpression.java:89)
	->at com.jetbrains...lambda$getType$0(TypeEvalContext.java:176)
	...
	->at java...run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
fixed with https://github.com/wt-io-it/odoo-pycharm-plugin/issues/33 (620508fc55b16691df8772f3239f21fd4f06be56, 0.5.17)

**Comment by ap-wtioit** [comment]
0.5.18 is now available in jetbrains marketplace https://plugins.jetbrains.com/plugin/13083-odoo-autocompletion-support
