### ISSUE TITLE
Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement

### ISSUE THREAD

**Issue by mdakash41** [wt-io-it/odoo-pycharm-plugin#48]
Plugin Version: 0.5.16
IDEA Version: PyCharm 2022.2

<details><summary>java.lang.Throwable: Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement</summary>

```
java.lang.Throwable: Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.getStringValueForValueChild(OdooModelUtil.java:121)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:42)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:28)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelDefinition.<init>(OdooModelDefinition.java:17)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.lambda$mapWatched$0(OdooModelFileIndex.java:114)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:50)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:111)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:14)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:308)
	...
	at com.intellij.util.indexing.FileBasedIndexEx.getAllKeys(FileBasedIndexEx.java:145)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.getModels(OdooModelServiceImpl.java:30)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.getModelNames(OdooModelServiceImpl.java:52)
	at at.wtioit.intellij.plugins.odoo.AbstractOdooAddonsCompletionContributor.suggestModelName(AbstractOdooAddonsCompletionContributor.java:73)
	at at.wtioit.intellij.plugins.odoo.OdooAddonsCompletionContributor.fillCompletionVariants(OdooAddonsCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	...
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	...
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by ap-wtioit** [comment]
@mdakash41 i tried to reproduce this in the tests (and couldn't). Do you still remember by any chance what cause the issue?

anything strange after `_name` or `_inherit`?

**Comment by mdakash41** [comment]
This problem is solved after reinstalling the plugin.
Thanks @ap-wtioit
