### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by blomblomski** [wt-io-it/odoo-pycharm-plugin#52]
Plugin Version: 0.5.18
IntelliJ Version: PyCharm 2022.1.3
IntelliJ Build: PC-221.5921.27

<details><summary>java.lang.Throwable: Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement
</summary>

```
java.lang.Throwable: Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.getStringValueForValueChild(OdooModelUtil.java:122)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:42)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:28)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelDefinition.<init>(OdooModelDefinition.java:17)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.lambda$mapWatched$0(OdooModelFileIndex.java:114)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:50)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:111)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:25)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:308)
	...
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
@blomblomski thanks for reporting, as mentioned in #48 i couldn't reproduce this in tests.

Can you hint me in the direction of what might have caused this? Anything out of the ordinary after `_inherit` or `_name`?
