### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#6]
i didn't do anything

<details>
```
java.lang.RuntimeException: testing error handler
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModule(OdooModuleServiceImpl.java:53)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:49)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:199)
```
</details>

**Comment by ap-wtioit** [comment]
Test issue for 4229dae49a8b414a066a0a1ac4d50f0b8f2a94ca
