### ISSUE TITLE
OdooRecords XML File, java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#61]
Plugin Version: 0.6.2
IntelliJ Version: PyCharm 2022.2.3
IntelliJ Build: PY-222.4345.23

<details><summary>Unhandled exception in [StandaloneCoroutine{Cancelling}@5c3ae105, EDT]</summary>

```
java.lang.StringIndexOutOfBoundsException: begin 14, end -1, length 66
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getOdooRecord(OdooGoToDeclarationHandler.java:88)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTarget(OdooGoToDeclarationHandler.java:72)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationHandlerBase.getGotoDeclarationTargets(GotoDeclarationHandlerBase.java:14)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTargets(OdooGoToDeclarationHandler.java:33)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProvidersInner(gtdProviders.kt:30)
	...
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:32)
	...
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2.invokeSuspend(CtrlMouseHandler.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	...
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

**Comment by bigbear3001** [comment]
Happens when you hold [CTRL] any point to any part before the string argument of ref:
```
[(6,0,[ref(
```

**Comment by ap-wtioit** [comment]
0.6.3 is approved and [now](https://github.com/wt-io-it/odoo-pycharm-plugin/issues/69) also shown for pycharm in marketplace
