### ISSUE TITLE
OdooRecords XML File, java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#62]
Plugin Version: 0.6.2
IntelliJ Version: PyCharm 2022.2.3
IntelliJ Build: PY-222.4345.23

<details><summary>Unhandled exception in [StandaloneCoroutine{Cancelling}@3f7a71bb, EDT]</summary>

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1515)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getOdooRecord(OdooGoToDeclarationHandler.java:86)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTarget(OdooGoToDeclarationHandler.java:72)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationHandlerBase.getGotoDeclarationTargets(GotoDeclarationHandlerBase.java:14)
	at at.wtioit.intellij.plugins.odoo.OdooGoToDeclarationHandler.getGotoDeclarationTargets(OdooGoToDeclarationHandler.java:33)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProvidersInner(gtdProviders.kt:30)
	...
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:32)
	...
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2.invokeSuspend(CtrlMouseHandler.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	...
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

**Comment by ap-wtioit** [comment]
slightly different exception than #61 but happens also with the same steps to reproduce

**Comment by bigbear3001** [comment]
happens when you hold [CTRL] and point to the position between `ref(` and the `'` quote

**Comment by ap-wtioit** [comment]
0.6.3 is approved and [now](https://github.com/wt-io-it/odoo-pycharm-plugin/issues/69) also shown for pycharm in marketplace
