### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by foxcarlos** [wt-io-it/odoo-pycharm-plugin#73]
Plugin Version: 0.6.6
IntelliJ Version: PyCharm 2022.2.3
IntelliJ Build: PY-222.4345.23

<details><summary>java.lang.NullPointerException: Cannot invoke "at.wtioit.intellij.plugins.odoo.records.OdooRecord.getDefiningElement()" because "record" is null</summary>

```
java.lang.NullPointerException: Cannot invoke "at.wtioit.intellij.plugins.odoo.records.OdooRecord.getDefiningElement()" because "record" is null
	at at.wtioit.intellij.plugins.odoo.AbstractOdooCompletionContributor.lambda$suggestRecordXmlId$1(AbstractOdooCompletionContributor.java:119)
	at at.wtioit.intellij.plugins.odoo.WithinProject.run(WithinProject.java:25)
	at at.wtioit.intellij.plugins.odoo.AbstractOdooCompletionContributor.suggestRecordXmlId(AbstractOdooCompletionContributor.java:118)
	at at.wtioit.intellij.plugins.odoo.OdooXmlCompletionContributor.fillCompletionVariants(OdooXmlCompletionContributor.java:22)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	...
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	...
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by ap-wtioit** [comment]
Happens when using xml like this for autocomplete:
```xml
<field name="inherit_id" ref=":UNDETECTED_XML_ID:.ec"/>
```
