### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by krunal267** [wt-io-it/odoo-pycharm-plugin#76]
Plugin Version: 0.6.6
IntelliJ Version: PyCharm 2022.2.3
IntelliJ Build: PC-222.4345.23

<details><summary>java.lang.Throwable: Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement</summary>

```
java.lang.Throwable: Unknown string value class: class com.intellij.psi.impl.source.tree.LeafPsiElement
	->at com.intellij...error(Logger.java:184)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.getStringValueForValueChild(PsiElementsUtil.java:219)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:37)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:23)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelIE.<init>(OdooModelIE.java:19)
	at at.wtioit.intellij.plugins.odoo.OdooModelPsiElementMatcherUtil.lambda$getModelsFromFile$2(OdooModelPsiElementMatcherUtil.java:348)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:120)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:108)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:98)
	at at.wtioit.intellij.plugins.odoo.OdooModelPsiElementMatcherUtil.getModelsFromFile(OdooModelPsiElementMatcherUtil.java:342)
	at at.wtioit.intellij.plugins.odoo.OdooModelPsiElementMatcherUtil.getModelsFromFile(OdooModelPsiElementMatcherUtil.java:337)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:112)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:25)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndexExtension.map(OdooIndexExtension.java:26)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndexer.lambda$map$0(OdooIndexer.java:20)
	->at java...accept(ReferencePipeline.java:197)
	...
	->at java...collect(ReferencePipeline.java:682)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndexer.map(OdooIndexer.java:22)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndexer.map(OdooIndexer.java:10)
	->at com.intellij...mapByIndexer(MapReduceIndex.java:308)
	...
	->at com.intellij...getValues(FileBasedIndexEx.java:136)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndex.getAllKeys(OdooIndex.java:62)
	at at.wtioit.intellij.plugins.odoo.models.impl.OdooModelServiceImpl.hasModel(OdooModelServiceImpl.java:76)
	at at.wtioit.intellij.plugins.odoo.models.inspection.MissingModelDefinitionInspection$1.visitElement(MissingModelDefinitionInspection.java:64)
	->at com.intellij...accept(LeafPsiElement.java:208)
	...
	->at java...run(ForkJoinWorkerThread.java:165)
```
</details>

**Comment by ap-wtioit** [comment]
@krunal267 thanks for reporting this, any chance you know the python code element (after `_name` / `_inherit`) this happened for?

as mentioned in #52 and #48 i could not reproduce this in tests
