### ISSUE TITLE
getModuleDirectorySlow java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by Triosof** [wt-io-it/odoo-pycharm-plugin#79]
Plugin Version: 0.5.15
IDEA Version: PyCharm 2022.2.3

<details><summary>java.lang.Throwable: Assertion failed</summary>

```
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:220)
	...
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:79)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.lambda$getModuleDirectorySlow$3(OdooModuleServiceImpl.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectorySlow(OdooModuleServiceImpl.java:134)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectory(OdooModuleServiceImpl.java:121)
	at at.wtioit.intellij.plugins.odoo.modules.index.OdooDeserializedModuleImpl.getDirectory(OdooDeserializedModuleImpl.java:64)
	at at.wtioit.intellij.plugins.odoo.WithinProject.call(WithinProject.java:15)
	at at.wtioit.intellij.plugins.odoo.modules.search.OdooModulePsiElement.getDirectory(OdooModulePsiElement.java:46)
	at at.wtioit.intellij.plugins.odoo.modules.search.OdooModulePsiElement.getContainingFile(OdooModulePsiElement.java:131)
	at com.intellij.psi.util.PsiUtilCore.getVirtualFile(PsiUtilCore.java:355)
	...
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:32)
	...
	at com.intellij.ide.util.PsiElementBackgroundPresentationComputer$doComputePresentationAsync$result$1.invokeSuspend(PsiElementBackgroundPresentationComputer.kt:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	...
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

**Comment by ap-wtioit** [comment]
@Triosof this is the same as #33 and was fixed in 0.5.18, can you update the plugin?
