### ISSUE TITLE
Indexing error resolving python expressions

### ISSUE THREAD

**Issue by ap-wtioit** [wt-io-it/odoo-pycharm-plugin#8]
Plugin Version: 0.5.9
IDEA Version: PyCharm 2021.3.2

<details><summary>java.lang.Throwable: Indexing process should not rely on non-indexed file data.</summary>

```
java.lang.Throwable: Indexing process should not rely on non-indexed file data.
Indexing file = /home/bigbear3001/Documents/workspace_docker/doodba-wtioit-dev/odoo/custom/src/odoo/odoo/addons/test_new_api/tests/test_new_fields.py, file id = 2702084, queried file id = 2701526
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	...
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.followAssignmentsChain(PyReferenceExpressionImpl.java:123)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.getStringValueForValueChild(OdooModelUtil.java:74)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:42)
	at at.wtioit.intellij.plugins.odoo.models.OdooModelUtil.detectName(OdooModelUtil.java:28)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelDefinition.<init>(OdooModelDefinition.java:17)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.lambda$mapWatched$0(OdooModelFileIndex.java:114)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:50)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:51)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:51)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:51)
	at at.wtioit.intellij.plugins.odoo.PsiElementsUtil.walkTree(PsiElementsUtil.java:51)
	at at.wtioit.intellij.plugins.odoo.models.index.OdooModelFileIndex$OdooModelFileIndexer.mapWatched(OdooModelFileIndex.java:111)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.lambda$map$0(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.IndexWatcher.runIndexJob(IndexWatcher.java:14)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:13)
	at at.wtioit.intellij.plugins.odoo.index.OdooDataIndexer.map(OdooDataIndexer.java:9)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:306)
	...
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaFilesForFile(JsonSchemaServiceImpl.java:156)
	at org.jetbrains.plugins.github.extensions.GithubYamlIconProvider.getIcon(GithubYamlIconProvider.kt:21)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:220)
	...
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by ap-wtioit** [comment]
after fixing #5 we still have an exception when testing with more real world data

**Comment by ap-wtioit** [comment]
Jetbrains just approved the plugin version 0.5.10. This should be fixed now.
