### ISSUE TITLE
Exception in Odoo Autocompletion Support

### ISSUE THREAD

**Issue by mahaElmorsy** [wt-io-it/odoo-pycharm-plugin#81]
Plugin Version: 0.6.6
IntelliJ Version: PyCharm 2022.2.3
IntelliJ Build: PC-222.4345.23

<details><summary>java.lang.IllegalStateException: Index is not created for `OdooIndex`
</summary>

```
java.lang.IllegalStateException: Index is not created for `OdooIndex`
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndex(FileBasedIndexImpl.java:1308)
	...
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:136)
	at at.wtioit.intellij.plugins.odoo.index.OdooIndex.getValues(OdooIndex.java:49)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.lambda$getModule$1(OdooModuleServiceImpl.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModule(OdooModuleServiceImpl.java:61)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:49)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:199)
	...
	at com.jetbrains.python.psi.impl.references.PyFromImportNameReference.resolveInner(PyFromImportNameReference.java:49)
	at dev.ngocta.pycharm.odoo.python.psi.OdooPyFromImportNameReference.resolveInner(OdooPyFromImportNameReference.java:34)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.multiResolveInner(PyReferenceImpl.java:107)
	...
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by ap-wtioit** [comment]
@mahaElmorsy do you know a way to reproduce this issue? i think it might by fixed together with #72 but i do not want to dismiss it before i can verify that it's actually fixed.
