### ISSUE TITLE
Windows:  Unexpected internal error near index 1

### ISSUE THREAD

**Issue by kanyijoshua** [wt-io-it/odoo-pycharm-plugin#9]
Plugin Version: 0.5.9
IDEA Version: PyCharm 2021.3.1

<details><summary>java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
</summary>

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	...
	at java.base/java.lang.String.split(String.java:2364)
	at at.wtioit.intellij.plugins.odoo.modules.impl.OdooModuleServiceImpl.getModuleDirectory(OdooModuleServiceImpl.java:106)
	at at.wtioit.intellij.plugins.odoo.modules.index.OdooDeserializedModuleImpl.getDirectory(OdooDeserializedModuleImpl.java:64)
	at at.wtioit.intellij.plugins.odoo.WithinProject.call(WithinProject.java:15)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:38)
	at at.wtioit.intellij.plugins.odoo.pycharm.PyCharmOdooAddonsImportResolver.resolveImportReference(PyCharmOdooAddonsImportResolver.java:42)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:199)
	...
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

**Comment by ap-wtioit** [comment]
Thanks for the report, i'm already working on a fix.

**Comment by ap-wtioit** [comment]
As i currently do not have a Windows development system available would you be so nice and test this version of the plugin that contains a fix for Windows:
* https://github.com/wt-io-it/odoo-pycharm-plugin/blob/master-0.5.10_fix_indexing_error/odoo_plugin.jar
* to install:
    * Download the above 0.5.10-SNAPSHOT version of the plugin
    * In PyCharm in File > Settings > Plugin select the gear icon.
    * Select install plugin from disk and choose the downloaded odoo_plugin.jar

**Comment by ap-wtioit** [comment]
Jetbrains just approved the plugin version 0.5.10. This should be fixed now.

**Comment by kanyijoshua** [comment]
Thanks it working now
